"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TagsOrder = exports.PostsOrder = exports.ImageResizeStrategy = exports.ImageResizeFocus = exports.ImageFormat = exports.EntryOrder = exports.AssetOrder = void 0;
var AssetOrder;
(function (AssetOrder) {
    AssetOrder["ContentTypeAsc"] = "contentType_ASC";
    AssetOrder["ContentTypeDesc"] = "contentType_DESC";
    AssetOrder["FileNameAsc"] = "fileName_ASC";
    AssetOrder["FileNameDesc"] = "fileName_DESC";
    AssetOrder["HeightAsc"] = "height_ASC";
    AssetOrder["HeightDesc"] = "height_DESC";
    AssetOrder["SizeAsc"] = "size_ASC";
    AssetOrder["SizeDesc"] = "size_DESC";
    AssetOrder["SysFirstPublishedAtAsc"] = "sys_firstPublishedAt_ASC";
    AssetOrder["SysFirstPublishedAtDesc"] = "sys_firstPublishedAt_DESC";
    AssetOrder["SysIdAsc"] = "sys_id_ASC";
    AssetOrder["SysIdDesc"] = "sys_id_DESC";
    AssetOrder["SysPublishedAtAsc"] = "sys_publishedAt_ASC";
    AssetOrder["SysPublishedAtDesc"] = "sys_publishedAt_DESC";
    AssetOrder["SysPublishedVersionAsc"] = "sys_publishedVersion_ASC";
    AssetOrder["SysPublishedVersionDesc"] = "sys_publishedVersion_DESC";
    AssetOrder["UrlAsc"] = "url_ASC";
    AssetOrder["UrlDesc"] = "url_DESC";
    AssetOrder["WidthAsc"] = "width_ASC";
    AssetOrder["WidthDesc"] = "width_DESC";
})(AssetOrder = exports.AssetOrder || (exports.AssetOrder = {}));
var EntryOrder;
(function (EntryOrder) {
    EntryOrder["SysFirstPublishedAtAsc"] = "sys_firstPublishedAt_ASC";
    EntryOrder["SysFirstPublishedAtDesc"] = "sys_firstPublishedAt_DESC";
    EntryOrder["SysIdAsc"] = "sys_id_ASC";
    EntryOrder["SysIdDesc"] = "sys_id_DESC";
    EntryOrder["SysPublishedAtAsc"] = "sys_publishedAt_ASC";
    EntryOrder["SysPublishedAtDesc"] = "sys_publishedAt_DESC";
    EntryOrder["SysPublishedVersionAsc"] = "sys_publishedVersion_ASC";
    EntryOrder["SysPublishedVersionDesc"] = "sys_publishedVersion_DESC";
})(EntryOrder = exports.EntryOrder || (exports.EntryOrder = {}));
var ImageFormat;
(function (ImageFormat) {
    ImageFormat["Avif"] = "AVIF";
    ImageFormat["Jpg"] = "JPG";
    ImageFormat["JpgProgressive"] = "JPG_PROGRESSIVE";
    ImageFormat["Png"] = "PNG";
    ImageFormat["Png8"] = "PNG8";
    ImageFormat["Webp"] = "WEBP";
})(ImageFormat = exports.ImageFormat || (exports.ImageFormat = {}));
var ImageResizeFocus;
(function (ImageResizeFocus) {
    ImageResizeFocus["Bottom"] = "BOTTOM";
    ImageResizeFocus["BottomLeft"] = "BOTTOM_LEFT";
    ImageResizeFocus["BottomRight"] = "BOTTOM_RIGHT";
    ImageResizeFocus["Center"] = "CENTER";
    ImageResizeFocus["Face"] = "FACE";
    ImageResizeFocus["Faces"] = "FACES";
    ImageResizeFocus["Left"] = "LEFT";
    ImageResizeFocus["Right"] = "RIGHT";
    ImageResizeFocus["Top"] = "TOP";
    ImageResizeFocus["TopLeft"] = "TOP_LEFT";
    ImageResizeFocus["TopRight"] = "TOP_RIGHT";
})(ImageResizeFocus = exports.ImageResizeFocus || (exports.ImageResizeFocus = {}));
var ImageResizeStrategy;
(function (ImageResizeStrategy) {
    ImageResizeStrategy["Crop"] = "CROP";
    ImageResizeStrategy["Fill"] = "FILL";
    ImageResizeStrategy["Fit"] = "FIT";
    ImageResizeStrategy["Pad"] = "PAD";
    ImageResizeStrategy["Scale"] = "SCALE";
    ImageResizeStrategy["Thumb"] = "THUMB";
})(ImageResizeStrategy = exports.ImageResizeStrategy || (exports.ImageResizeStrategy = {}));
var PostsOrder;
(function (PostsOrder) {
    PostsOrder["CreatedAtAsc"] = "createdAt_ASC";
    PostsOrder["CreatedAtDesc"] = "createdAt_DESC";
    PostsOrder["SlugAsc"] = "slug_ASC";
    PostsOrder["SlugDesc"] = "slug_DESC";
    PostsOrder["SysFirstPublishedAtAsc"] = "sys_firstPublishedAt_ASC";
    PostsOrder["SysFirstPublishedAtDesc"] = "sys_firstPublishedAt_DESC";
    PostsOrder["SysIdAsc"] = "sys_id_ASC";
    PostsOrder["SysIdDesc"] = "sys_id_DESC";
    PostsOrder["SysPublishedAtAsc"] = "sys_publishedAt_ASC";
    PostsOrder["SysPublishedAtDesc"] = "sys_publishedAt_DESC";
    PostsOrder["SysPublishedVersionAsc"] = "sys_publishedVersion_ASC";
    PostsOrder["SysPublishedVersionDesc"] = "sys_publishedVersion_DESC";
    PostsOrder["TitleAsc"] = "title_ASC";
    PostsOrder["TitleDesc"] = "title_DESC";
})(PostsOrder = exports.PostsOrder || (exports.PostsOrder = {}));
var TagsOrder;
(function (TagsOrder) {
    TagsOrder["NameAsc"] = "name_ASC";
    TagsOrder["NameDesc"] = "name_DESC";
    TagsOrder["SlugAsc"] = "slug_ASC";
    TagsOrder["SlugDesc"] = "slug_DESC";
    TagsOrder["SysFirstPublishedAtAsc"] = "sys_firstPublishedAt_ASC";
    TagsOrder["SysFirstPublishedAtDesc"] = "sys_firstPublishedAt_DESC";
    TagsOrder["SysIdAsc"] = "sys_id_ASC";
    TagsOrder["SysIdDesc"] = "sys_id_DESC";
    TagsOrder["SysPublishedAtAsc"] = "sys_publishedAt_ASC";
    TagsOrder["SysPublishedAtDesc"] = "sys_publishedAt_DESC";
    TagsOrder["SysPublishedVersionAsc"] = "sys_publishedVersion_ASC";
    TagsOrder["SysPublishedVersionDesc"] = "sys_publishedVersion_DESC";
})(TagsOrder = exports.TagsOrder || (exports.TagsOrder = {}));
